#application.yml：主配置文件，通常存放所有环境共用的基础配置，
#例如应用名称、端口号、日志级别等。它不会被直接覆盖，而是作为“默认值”被其他环境配置文件继承或补充。
spring:
  application:
    name: App-Server

#    这样项目在本地开发时就会自动使用 application-dev.yml 的配置；
#部署到服务器时，改为 active: prod 即可无缝切换到生产配置。
  profiles:
    active: dev





