#application-dev.yml：开发环境专用配置文件。
#当项目以 dev 模式启动时（通过 spring.profiles.active=dev 指定），
#Spring Boot 会自动加载此文件，并将其中的配置与 application.yml 合并，
#优先级更高。常用于配置本地数据库地址、调试开关、测试接口等。


#数据库配置（windows）
datasource:
  url: jdbc:mysql://localhost:3306/tianshuwaimai?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  username: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver

# Mybaits配置
mybatis:
  configuration:
    # SQL语句打印到控制台，生产环境请关闭
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 配置SQL语句的格式化
    format: true



# 阿里云配置
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com  # 替换为您的 Bucket 对应地域节点
    access-key-id: ${ALIBABA_CLOUD_ACCESS_KEY_ID}     # 推荐使用环境变量，避免明文
    access-key-secret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
    bucket-name: tianshuwaimai         # 替换为您的 Bucket 名称





#配置文件配置 JWT密钥
jwt:
  secret: "jwt_secret_key_ZZCJWT1234567890abcdef"           # JWT密钥
  expire: 86400                                             # JWT过期时间，单位秒





